### ISSUE TITLE
Global layout data not working

### ISSUE THREAD

**Issue by janherman** [getkirby/layouts#1]
I tried to pass some data to the layout method, but I get "Undefined variable" error every time. 

My template: 
/site/templates/default.php

```php
<?php layout("default", ["title" => "Some title"]) ?>

<p>Some content...</p>
```

Layout:
/site/layouts/default.php
```php
<?= $title ?>

<?php slot() ?>
<?php endslot() ?>
```

Latest version of Kirby Plainkit, no other plugins installed.

**Comment by afbora** [comment]
Did you try in slots? Like that:

````php
<?php slot() ?>
  <?= $title ?>
<?php endslot() ?>

**Comment by janherman** [comment]
Yes, I tried that. Unfortunately it does not work either.
