### ISSUE TITLE
Cannot install on PHP 8.2 with composer

### ISSUE THREAD

**Issue by fvsch** [getkirby/layouts#10]
Hi there,

This issue was reported in https://github.com/getkirby/layouts/issues/9 and marked as fixed, but the fix was never published to Packagist, so in practice it's still not possible to `composer require getkirby/layouts` with PHP 8.2.

**Comment by fvsch** [comment]
For the record, I've used a couple workarounds.

First, I changed my `composer.json` to install this plugin from GitHub directly:

```json
{
	"require": {
		"php": ">=8.0.0 <8.3.0",
		"getkirby/cms": "^3.9.4",
		"getkirby/layouts": "dev-main"
	},
	"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/getkirby/layouts"
		}
	],
}
```

That works pretty well.

Then, after looking at this plugin source in the `site/plugins/layouts` folder that this will install, and seeing that it's a very simple shortcut, I decided to just hardcode a `site/plugins/layouts/index.php` file with a copy and some tweaks to help Intelephense:

```php
<?php

use Kirby\Template\Snippet;

/**
 * Helper function that captures the content following it as slots,
 * and renders it in a layout template.
 * Similar to using `snippet($name, slots: true)`, with a different
 * lookup path (looks in `site/layouts` instead of `site/snippets`).
 */
function layout($name = 'default', ?array $data = [])
{
	return Snippet::begin(
		file: kirby()->root('site') . '/layouts/' . $name . '.php',
		data: $data
	);
}

/**
 * Stops capturing content for the layout.
 * Similar to `endsnippet()`.
 */
function endlayout() {
	Snippet::end();
}
```

**Comment by afbora** [comment]
Sorry for the delay:
https://github.com/getkirby/layouts/releases/tag/2.0.1
