### ISSUE TITLE
Layout extending Layout

### ISSUE THREAD

**Issue by S1SYPHOS** [getkirby/layouts#3]
Hello there,
would it be possible for a layout to extend a layout? Eg layout `blog` calls `layouts/default.php` via `layout()`?

Thanks!

**Comment by bnomei** [comment]
👍

**Comment by S1SYPHOS** [comment]
For my latest project, I switched to @afbora's blade package, but still it would be nice for simple(r) projects to see this feature 😄

**Comment by bastianallgeier** [comment]
This is now possible with snippets with slots in 3.9
