### ISSUE TITLE
Nesting `slot()`s

### ISSUE THREAD

**Issue by S1SYPHOS** [getkirby/layouts#4]
Hey there,
I would like to nest slots - take the following scenario:

```php
<?php slot('content') ?>
<section class="container">
    <?php slot() ?>
    some default content
    <?php endslot() ?>
</section>
<?php endslot() ?>
```

Most of the time, my templates would use `slot()`, drop some content, maybe `echo $page->myfield()->toBlocks()` etc but some templates would need to remove the `container` element and do something completely different. IMHO nesting slots would make this way more DRY, wouldn't it?

Thanks for considering this and have a good day,
S1SYPHOS

**Comment by bastianallgeier** [comment]
This is solved with our new snippets with slots in 3.9
