### ISSUE TITLE
Add ability to define layouts in plugins

### ISSUE THREAD

**Issue by HYR** [getkirby/layouts#5]
Would love to have the ability to register layouts via a plugin instead of having to have inside of the `site/layouts` folder.

## Any Plugin Index.php
```php
'layouts'     => [
    'default' => __DIR__ . '/layouts/default.php',
    'blog' => __DIR__ . '/layouts/blog.php',
    …
],
```

Related forum post: https://forum.getkirby.com/t/how-do-i-register-layouts-in-plugins/25455

**Comment by fabianmichael** [comment]
I just played around with the plugin and wondered why the plugin does not just use `templates/layouts` as the default part for storing layouts. That way, layouts could be registered without the need of a whole new extension API.

**Comment by lukasbestle** [comment]
Our goal is to merge the layouts plugin into the core at some point. Then we'll also be able to easily provide a plugin extension for this feature.

**Comment by bastianallgeier** [comment]
This is now possible with our snippets with slots in 3.9
